[package]
name = "evilset"
version = "0.1.0"
authors = ["Sayantan Khan <sayantangkhan@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "0.17"
egui = {version = "0.17", features = ["multi_threaded"]}
serde = { version = "1", features = ["derive"], optional = true }
image = { version = "0.23", default-features = false, features = ["png"] }
cardgen = { path = "../cardgen" }
setengine = { path = "../setengine" }
poll-promise = "0.1"

[features]
default = []
persistence = ["eframe/persistence", "serde"] # Enable if you want to persist app state on shutdown

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"